import { getWordsByLanguage, normalizeText } from './words';

type Language = 'pt' | 'en' | 'es';

// Lists are generated by scripts/build-dictionaries.mjs and loaded lazily so only
// the active language is downloaded.
const loaders: Record<Language, () => Promise<{ default: string }>> = {
  pt: () => import('./dictionaries/pt.txt?raw'),
  en: () => import('./dictionaries/en.txt?raw'),
  es: () => import('./dictionaries/es.txt?raw'),
};

const cache: Partial<Record<Language, Set<string>>> = {};
const pending: Partial<Record<Language, Promise<Set<string>>>> = {};

export function loadDictionary(lang: Language): Promise<Set<string>> {
  if (cache[lang]) return Promise.resolve(cache[lang]);
  pending[lang] ??= loaders[lang]().then(({ default: raw }) => {
    const words = new Set(raw.split('\n').filter(Boolean));
    // Every possible answer must always be accepted as a guess.
    for (const entry of getWordsByLanguage(lang)) {
      words.add(normalizeText(entry.word));
    }
    cache[lang] = words;
    return words;
  }).catch((error) => {
    delete pending[lang];
    throw error;
  });
  return pending[lang];
}

/**
 * Returns whether the normalized guess is a known word. Returns null while the
 * dictionary for the language has not finished loading.
 */
export function isKnownWord(guess: string, lang: Language): boolean | null {
  const words = cache[lang];
  if (!words) return null;
  return words.has(normalizeText(guess));
}
